import Head from 'next/head'
import Header from "../components/Header";
import NavBar from "../components/NavBar";
import MainContent from "../components/MainContent";
import requests from "../utils/requests";

export default function Home({results}) {
  return (
    <div>
      <Head>
        <title>Hulu</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        {/*Header*/}
        <Header/>
        {/*NabBar*/}
        <NavBar/>
        {/*MainContent*/}
        <MainContent results={results}/>
    </div>
  )
}
export async function getServerSideProps(context){
  const genre = context.query.genre

  const req = await fetch(`https://api.themoviedb.org/3${requests[genre]?.url || requests.fetchTrending.url}`)
      .then(res=> res.json())

    return{
        props: {
          results: req.results
        }
    }

}
